%Solve for 12 Lead Seperation Formula

%Define Leads
syms I II III V1 V2 V3 V4 V5 V6
%Define Electrodes
syms LA RA LL RL v1 v2 v3 v4 v5 v6
Electrodes = [LA RA LL RL v1 v2 v3 v4 v5 v6];
%Define Lead Definitions
Leads = [
%I == LA - RA,...
II == LL - RA,...
III == LL - LA...
V1 == v1 - (RA+LA+LL)/3,...
V2 == v2 - (RA+LA+LL)/3,...
V3 == v3 - (RA+LA+LL)/3,...
V4 == v4 - (RA+LA+LL)/3,...
V5 == v5 - (RA+LA+LL)/3,...
V6 == v6 - (RA+LA+LL)/3 ...
];

Leads = subs(Leads,RA,0);
S = solve(Leads,[LA,LL,v1 v2 v3 v4 v5 v6],'IgnoreAnalyticConstraints',true)
