% Compute power spectrum

% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 11-Jan-2020 12:52:39

% Parameters
timeLimits = [0.001 60]; % seconds
frequencyLimits = [0 150]; % Hz
timeValues = 0::1/;

%%
% Index into signal time region of interest
Signal_ROI = Signal(:);
timeValues = t;
minIdx = timeValues >= timeLimits(1);
maxIdx = timeValues <= timeLimits(2);
Signal_ROI = Signal_ROI(minIdx&maxIdx);
timeValues = timeValues(minIdx&maxIdx);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[PSignal_ROI, FSignal_ROI] = pspectrum(Signal_ROI,timeValues, ...
    'FrequencyLimits',frequencyLimits);
